--------------------------------------------------------
--  DDL for Table GYM_TRAINER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."GYM_TRAINER" 
   (	"T_ID" NUMBER(3,0), 
	"T_NAME" VARCHAR2(10 CHAR), 
	"T_PHONE" VARCHAR2(13 CHAR), 
	"T_GENDER" VARCHAR2(2 CHAR), 
	"T_EMAIL" VARCHAR2(100 CHAR), 
	"T_SALARY" NUMBER(8,0), 
	"T_BIRTHDAY" DATE, 
	"T_HIREDATE" DATE, 
	"T_ADDRESS" VARCHAR2(300 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GYM_TRAINER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."GYM_TRAINER_PK" ON "SCOTT"."GYM_TRAINER" ("T_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger GYM_TRAINER_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."GYM_TRAINER_TRG" 
BEFORE INSERT ON GYM_TRAINER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."GYM_TRAINER_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table GYM_TRAINER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."GYM_TRAINER" MODIFY ("T_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GYM_TRAINER" MODIFY ("T_PHONE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GYM_TRAINER" MODIFY ("T_GENDER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GYM_TRAINER" MODIFY ("T_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GYM_TRAINER" ADD CONSTRAINT "GYM_TRAINER_PK" PRIMARY KEY ("T_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
