--------------------------------------------------------
--  DDL for Table MEMBERSHIP
--------------------------------------------------------

  CREATE TABLE "SCOTT"."MEMBERSHIP" 
   (	"MEMBERSHIP_CODE" NUMBER(3,0), 
	"MEMBERSHIP_NUMOFDAYS" NUMBER(5,0), 
	"MEMBERSHIP_PRICE" NUMBER(9,0), 
	"MEMBERSHIP_CATEGORY" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBERSHIP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."MEMBERSHIP_PK" ON "SCOTT"."MEMBERSHIP" ("MEMBERSHIP_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger MEMBERSHIP_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."MEMBERSHIP_TRG" 
BEFORE INSERT ON MEMBERSHIP 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."MEMBERSHIP_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBERSHIP
--------------------------------------------------------

  ALTER TABLE "SCOTT"."MEMBERSHIP" MODIFY ("MEMBERSHIP_NUMOFDAYS" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBERSHIP" MODIFY ("MEMBERSHIP_PRICE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBERSHIP" MODIFY ("MEMBERSHIP_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBERSHIP" ADD CONSTRAINT "MEMBERSHIP_PK" PRIMARY KEY ("MEMBERSHIP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
